default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: volodymyrpivtoranis
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: internship_test_pivtoranis_v_development

test:
  <<: *default
  database: internship_test_pivtoranis_v_test

production:
  primary: &primary_production
    <<: *default
    database: internship_test_pivtoranis_v_production
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    database: internship_test_pivtoranis_v_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: internship_test_pivtoranis_v_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: internship_test_pivtoranis_v_production_cable
    migrations_paths: db/cable_migrate
